import type { Lead, LeadNote } from '../types/lead';

export const initialMockLeads: Lead[] = [
  {
    id: 'lead-001',
    name: 'Rajesh Sharma',
    phone: '+91 98220 12345',
    business_name: 'Sharma Sweets & Dairy',
    status: 'Follow-up',
    follow_up_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(), // Overdue 2 hours ago
    last_contacted_at: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    created_at: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    address: 'Shop 12, Main Market, Tasgaon, Maharashtra',
    google_business_url: 'https://maps.google.com/?q=Sharma+Sweets+Tasgaon',
    instagram_url: 'https://instagram.com/sharmasweets',
    website_url: null,
    source: 'Cold Call',
  },
  {
    id: 'lead-002',
    name: 'Anand Kulkarni',
    phone: '+91 91580 98765',
    business_name: 'Kulkarni Auto Repairs',
    status: 'Interested',
    follow_up_at: new Date(Date.now() + 4 * 3600 * 1000).toISOString(), // Today +4 hours
    last_contacted_at: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
    created_at: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    address: 'MIDC Area, Block C, Sangli',
    google_business_url: 'https://maps.google.com/?q=Kulkarni+Auto+Sangli',
    instagram_url: null,
    website_url: null,
    source: 'Google Search',
  },
  {
    id: 'lead-003',
    name: 'Suresh Patil',
    phone: '+91 94230 55443',
    business_name: 'Patil Hardware & Electricals',
    status: 'New',
    follow_up_at: new Date(Date.now() + 2 * 24 * 3600 * 1000).toISOString(), // +2 days
    last_contacted_at: null,
    created_at: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    address: 'Station Road, Miraj',
    google_business_url: null,
    instagram_url: null,
    website_url: null,
    source: 'Referral',
  },
  {
    id: 'lead-004',
    name: 'Priya Joshi',
    phone: '+91 70833 30914',
    business_name: 'Joshi Boutique & Tailors',
    status: 'Won',
    follow_up_at: null,
    last_contacted_at: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
    created_at: new Date(Date.now() - 10 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    address: 'College Corner, Kolhapur',
    google_business_url: 'https://maps.google.com',
    instagram_url: 'https://instagram.com/joshiboutique',
    website_url: 'https://joshiboutique.com',
    source: 'Instagram Lead',
  },
  {
    id: 'lead-005',
    name: 'Vikas Jadhav',
    phone: '+91 98900 11223',
    business_name: 'Jadhav Dental Clinic',
    status: 'Proposal Sent',
    follow_up_at: new Date(Date.now() + 1 * 24 * 3600 * 1000).toISOString(), // Tomorrow
    last_contacted_at: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
    created_at: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    address: 'Opposite Government Hospital, Karad',
    google_business_url: null,
    instagram_url: null,
    website_url: null,
    source: 'Cold Visit',
  },
];

export const initialMockNotes: LeadNote[] = [
  {
    id: 'note-001',
    lead_id: 'lead-001',
    note: 'Initial call made to owner Rajesh. He requested a basic 5-page catalog website for his sweet shop with WhatsApp ordering button.',
    type: 'Call',
    created_at: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'note-002',
    lead_id: 'lead-002',
    note: 'Sent proposal PDF via WhatsApp. Client reviewed and expressed strong interest in GBP optimization bundle.',
    type: 'WhatsApp',
    created_at: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
  },
  {
    id: 'note-003',
    lead_id: 'lead-004',
    note: 'Payment received ₹12,000 for static portfolio website + Instagram branding. Project started.',
    type: 'Meeting',
    created_at: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
  },
];
